kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: hello-nginx
  name: hello-nginx
  namespace: demo-pic
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: hello-nginx
  template:
    metadata:
      labels:
        app: hello-nginx
    spec:
      containers:
      - name: hello-nginx
        image: IMAGE
        imagePullPolicy: Always
        ports:
          - name: web
            containerPort: 80
      imagePullSecrets:
        - name: docker-registry-config