apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-nginx
  name: hello-nginx
  namespace: demo-pic
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: hello-nginx
  template:
    metadata:
      labels:
        app: hello-nginx
    spec:
      containers:
      - name: hello-nginx
        image: registry.demo-pic.techlead-top.ovh/hello-nginx:latest
        imagePullPolicy: Always
        ports:
          - name: web
            containerPort: 80
      imagePullSecrets:
        - name: docker-registry-config